src/DndOverlordHomePage/Models/Character.cs
using System.Data;

namespace DndOverlordHomePage.Models;


public class Character : Creature
{
    public Character(){}
    public Character(IDataReader reader)
    {
        
    }
}

src/DndOverlordHomePage/Models/Creature.cs
namespace DndOverlordHomePage.Models;

public class StatBlock
{
    public int Strength { get; set; }
    public int Dexterity { get; set; }
    public int Constitution { get; set; }
    public int Intelligence { get; set; }
    public int Wisdom { get; set; }
    public int Charisma { get; set; }
    public int ProficiencyBonus { get; set; }
}

public class Experience
{
    public int Level { get; private set; }
    private long ExperiencePoints { get; set; }
    public void AddExperience(long experiencePointsToAdd) => ExperiencePoints += experiencePointsToAdd;
    public void SubtractExperience(long experiencePointsToRemove) => ExperiencePoints -= experiencePointsToRemove;
}

public class Creature
{
    public int CR { get; set; }
    public Experience Experience { get; set; }
    public int TotalHealth { get; set; }
    public int CurrentHealth { get; set; }
    public int TemporaryHealth { get; set; }
    public string Name { get; set; }
    public Wallet Wallet { get; set; }
    public List<Item> ItemList { get; set; }

    
    public void FullHeal() => CurrentHealth = TotalHealth;
    public void DamageCreature(int damage)
    {
        if (TemporaryHealth > 0)
        {
            if (TemporaryHealth > damage) TemporaryHealth -= damage;
            else CurrentHealth -= (damage - TemporaryHealth);
        }
        else
        {
            CurrentHealth -= damage;
            //TODO: calculate if damage < 0, start death save?
            if (CurrentHealth < 0) CurrentHealth = 0;
        }
    }

    public void HealCreature(int healing)
    {
        CurrentHealth += healing;
        if (CurrentHealth > TotalHealth) CurrentHealth = TotalHealth;
    }
}

public class SpellSlot
{
    public int Level { get; set; }
    public long NumberOfSpells { get; set; }
}

src/DndOverlordHomePage/Models/Currency.cs
namespace DndOverlordHomePage.Models;


public class Currency
{
    public CurrencyType CurrencyType { get; set; }
    public long ValueInCopper { get; set; }
}

public enum CurrencyType {
    Copper, 
    Silver,
    Electrum,
    Gold,
    Platinum
}

public class Wallet
{
    public Wallet(){ }

    public Dictionary<CurrencyType, long> ConversionHashMap = new Dictionary<CurrencyType, long>()
    {
        { CurrencyType.Copper, 1 },
        { CurrencyType.Silver, 10 },
        { CurrencyType.Electrum, 50 },
        { CurrencyType.Gold, 100 },
        { CurrencyType.Platinum, 1000 }
    };
    public long Gold { get; set; }
    public long Silver { get; set; }
    public long Copper { get; set; }
    public long Electrum { get; set; }
    public long Platinum { get; set; }
    
    
    public void SetWallet(long gold, long silver, long copper, long electrum,long platiunum)
    {
        Gold = gold;
        Silver = silver;
        Copper = copper;
        Electrum = electrum;
        Platinum = platiunum;
    }

    public long ConvertToCopper(long currencyValue, CurrencyType currencyType)
    {
        return currencyValue *  ConversionHashMap[currencyType];
    }
}

src/DndOverlordHomePage/Models/Dice.cs
namespace DndOverlordHomePage.Models;


public class Dice {

    public int numSides { get; set; }

    public static int RollDice(int numSides)
    {
        var random = new Random();
        return random.Next(1, numSides);
    }

    public static int RollDie(int numSides, int numRolls)
    {
        var output = 0;
        for (var i = 0; i < numRolls; i++)
            output += RollDice(numSides);
        
        return output;
    }
}

src/DndOverlordHomePage/Models/ErrorViewModel.cs
namespace DndOverlordHomePage.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

src/DndOverlordHomePage/Models/Feat.cs
namespace DndOverlordHomePage.Models;


public class Feat
{
    public string Name { get; set; }
    public string Description { get; set; }
    public int Uses { get; set; }
    
}

src/DndOverlordHomePage/Models/Item.cs
namespace DndOverlordHomePage.Models;

public class Item
{
    public Item(){}
    public Item(string name, string description, long value)
    {
        Name = name;
        Description = description;
        Value = value;
    }
    public string Name { get; set; }
    public string Description { get; set; }
    public long Value { get; set; }
    public CurrencyType ValueCurrency { get; set; }
}

public class Weapon : Item
{
    public int DamageDie { get; set; }
    public int NumDamageDie { get; set; }
    public long RollDamage() => Dice.RollDie(DamageDie, NumDamageDie);
}

src/DndOverlordHomePage/Models/Spell.cs
namespace DndOverlordHomePage.Models;

public class Spell : Weapon
{
    public bool Concentration { get; set; }
    public SchoolOfMagic MagicSchool { get; set; }
}

public enum SchoolOfMagic
{
    Conjuration, 
    Necromancy, 
    Evocation, 
    Abjuration, 
    Transmutation, 
    Divination, 
    Enchantment, 
    Illusion
}

src/DndOverlordHomePage/Controllers/CharacterController.cs
using System.Diagnostics;
using DndOverlordHomePage.Models;
using DndOverlordHomePage.Repositories;
using Microsoft.AspNetCore.Mvc;

namespace DndOverlordHomePage.Controllers;

public class CharacterController : Controller
{
    private readonly ILogger<CharacterController> _logger;

    public CharacterController(ILogger<CharacterController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        var characterRepository = new CharacterRepository();
        var characterList = characterRepository.GetCharacterList();
        return View("ViewCharacterList");
    }
    
    public IActionResult View(){
        var characterRepository = new CharacterRepository();

        //TODO: take in character ID
        var characterID = 1;
        var characterList = characterRepository.Get(characterID);
        return View("ViewCharacter");
    }
    
    public IActionResult Edit(){
        return View("NewUpdateCharacter");
    }
    
    public IActionResult New(){
        return View("NewUpdateCharacter");
    }
    
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

src/DndOverlordHomePage/Controllers/DiceController.cs
using System.Diagnostics;
using DndOverlordHomePage.Models;
using Microsoft.AspNetCore.Mvc;

namespace DndOverlordHomePage.Controllers;

public class DiceController : Controller
{
    private readonly ILogger<DiceController> _logger;

    public DiceController(ILogger<DiceController> logger)
    {
        _logger = logger;
    }

    public IActionResult DiceRoller()
    {
        return View();
    }
    
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

src/DndOverlordHomePage/Controllers/HomeController.cs
using System.Diagnostics;
using DndOverlordHomePage.Models;
using Microsoft.AspNetCore.Mvc;

namespace DndOverlordHomePage.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

src/DndOverlordHomePage/Views/Character/NewUpdateCharacter.cshtml
@{
    Layout = "_Layout";
}

<!DOCTYPE html>

<html>
<script src="~/js/Character.js" asp-append-version="true"></script>
<head>
    <title id="CharacterEditor">Character Editor</title>
</head>
<body>
<div id="CharacterInfo">
        Character Name<br/>
        <input type="text" id="characterName"/><br/>
        Character Bio<br/>
        <input type="text" name="characterBio" id="characterBio"/><br/>
        <br/>
        Race<br/>
        <select name="race">
          <option value="Dwarf">Elf</option>
          <option value="Elf">Elf</option>
          <option value="Eladrin">Eladrin</option>
        </select>

</div>
</body>
</html>

src/DndOverlordHomePage/Views/Character/ViewCharacter.cshtml
@{
    Layout = "_Layout";
}



<!DOCTYPE html>

<html>
<script src="~/js/Character.js" asp-append-version="true"></script>
<head>
    <title id="CharacterEditor">View Characters</title>
</head>
<body>
<div id="CharacterInfo">
    Character Name:<br/>
    <input type="text" id="characterName" disabled="disabled" value="test Name"/><br/>
    Character Bio:<br/>
    <input type="text" name="characterBio" id="characterBio"  disabled="disabled" value="test bio"/><br/>
    <br/>
    Race<br/>
    <select name="race" disabled="disabled">
        <option value="Dwarf" selected="selected">Elf</option>
        <option value="Elf">Elf</option>
        <option value="Eladrin">Eladrin</option>
    </select>
</div>
</body>
</html>

src/DndOverlordHomePage/Views/Character/ViewCharacterList.cshtml
@{
    Layout = "_Layout";
}

<!DOCTYPE html>

<html>
<script src="~/js/Character.js" asp-append-version="true"></script>
<head>
    <title id="CharacterEditor">View Characters</title>
</head>
<body>

<input type="button" value="New" onclick="location.href='@Url.Action("New", "Character")'" />

<div id="CharacterInfo">
    <table>
        <thead>CharacterName</thead>
        <thead>Class</thead>
        <thead>Level</thead>
        <thead>Action</thead>
        <tbody>
        <tr>
            <td>Swampy</td>
            <td>Druid</td>
            <td>20</td>
            <td>
                <input type="button" value="Edit" onclick="location.href='@Url.Action("Edit", "Character")'" />
                <input type="button" value="View" onclick="location.href='@Url.Action("View", "Character")'" />
            </td>
        </tr>
        </tbody>
    </table>
</div>
</body>
</html>

src/DndOverlordHomePage/Views/Dice/DiceRoller.cshtml
@{
    Layout = "_Layout";
}

<!DOCTYPE html>

<html>
<script src="~/js/DiceRoller.js" asp-append-version="true"></script>
<head>
    <title>Dice Roller Page</title>
</head>
<body>
<div id="RollingInputs">
    <p>
        Number of dice to roll<br/>
        <input type="text" id="numberOfDiceToRoll"/><br/>
        Number of sides per dice<br/>
        <input type="text" id="diceSides"/><br/>
        <button id="RollDice" onclick="Roll()" type="button">Roll Dice</button>
        <br/>
        Roll: <input type="text" disabled="disabled" id="rollOutputBox"/>
    </p>
</div>
</body>
</html>

src/DndOverlordHomePage/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p> This web app contains tools to help simplify DND related things</p>
    <p> Currently runs off MSSQL database,.NET MVC, and jQuery as tech stack </p>
</div>

src/DndOverlordHomePage/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - DND Overlord</title>
    
    <!-- css -->
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/DndOverlordHomePage.styles.css" asp-append-version="true"/>
    
    <!-- Scripts -->
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3 ">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">DndOverlordHomePage</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Dice" asp-action="DiceRoller">Dice</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Character" asp-action=Index>Character Manager</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>

<!-- This section renders the body of the application -->
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2023 - DndOverlordHomePage - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
</footer>
</body>
</html>